FROM node:23.8.0-alpine
RUN apk add --no-cache bash
WORKDIR /app
COPY package*.json ./
RUN npm install -g pnpm
RUN pnpm install
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate dev && pnpm run dev"]