FROM node:23.8-alpine AS base
WORKDIR /app
RUN apk add --no-cache openssl bash
RUN npm install -g pnpm
RUN npm install -g typescript

FROM base AS deps
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

FROM base AS build
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm build

FROM node:23.8-alpine AS runner
WORKDIR /app
RUN apk add --no-cache openssl bash
RUN npm install -g pnpm
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=build /app/dist ./dist

EXPOSE 8080

CMD ["pnpm", "run", "start"]